### ISSUE TITLE
Source of inhibition constants for CYP1A2 not clear

### ISSUE THREAD

**Issue by AndreDlm** [Open-Systems-Pharmacology/Fluvoxamine-Model#3]
I could not reconstruct where the following values of the inhibition constants for CYP1A2 (mixed inhibition) come from: 

![Annotation 2020-04-22 161833](https://user-images.githubusercontent.com/26541603/79993353-f3f32780-84b4-11ea-83b8-d4458a34e903.png)

@LMFuhr can you help out? Thanks!

**Comment by LMFuhr** [comment]
Hi @AndreDlm,

To describe the inhibition of CYP1A2 by fluvoxamine, the reported Ki value of 11 nmol/l (Karjalainen et al. 2008) was corrected for fluvoxamine binding in the in vitro test system as recommended by Yao et al. 2001.

The resulting Ki of 10 nmol/L was then used in the model.

You can find detailled information on the calculation of the Ki value in the Supplementary Material of @HannahBri 's publication ([PBPK models for CYP1A2 DDI prediction](https://doi.org/10.1002/psp4.12397)):

[Supplementary Material, Section 3.2](https://ascpt.onlinelibrary.wiley.com/action/downloadSupplement?doi=10.1002%2Fpsp4.12397&file=psp412397-sup-0008-SupplementS1.pdf)

Feel free to contact us if you have any more questions.

Best regards,
Laura

**Comment by AndreDlm** [comment]
Hi @LMFuhr and @HannahBri,

thanks for your fast feedback - I still have some questions, though :)
It seems that the inhibitor constant of 11 nmol/L reported by [Karjalainen 2008](https://onlinelibrary.wiley.com/doi/full/10.1111/j.1742-7843.2008.00252.x) was estimated from a competitive inhibition model, so that won't be readily transferable to a mixed-type inhibition model.

[Yao 2001](https://ascpt.onlinelibrary.wiley.com/doi/abs/10.1016/S0009-9236(01)62844-3) on the other side fitted a mixed-type inhibition model to the data, but they did not report values for alpha or K<sub>i,u</sub>.

Can you help out or does the model need a refinement/update?
Thanks a lot!

Best regards,
André
